mass_arm: [5,0,0,0,0,0,
           0,5,0,0,0,0,
           0,0,5,0,0,0,
           0,0,0,5,0,0,
           0,0,0,0,5,0,
           0,0,0,0,0,5]
damping_arm: [100,0,0,0,0,0,
              0,100,0,0,0,0,
              0,0,100,0,0,0,
              0,0,0,100,0,0,
              0,0,0,0,100,0,
              0,0,0,0,0,100]
stiffness_coupling: [100,0,0,0,0,0,
                     0,100,0,0,0,0,
                     0,0,100,0,0,0,
                     0,0,0,100,0,0,
                     0,0,0,0,100,0,
                     0,0,0,0,0,100]

damping_car: [15,0,0,0,0,0,
              0,15,0,0,0,0,
              0,0,15,0,0,0,
              0,0,0,15,0,0,
              0,0,0,0,15,0,
              0,0,0,0,0,15]

# base_link:  $(arg tf_prefix)base_link
# end_link:   $(arg tf_prefix)wrist_3_link
# [position (x, y, z)  orientation (x, y, z, w)]
desired_pose:  [0.5, 0.0, 0.5, 0.0, 0.707, 0.0, 0.707]

workspace_limits: [-0.50, 0.50, 0.25, 0.80, 0.30, 0.75]

arm_max_vel: 1.5
arm_max_acc: 1.0
platform_max_vel: 0.1
platform_max_acc: 0.2